version: "3.5"

services:
  text-embeddings-inference:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.6
    command: --model-id BAAI/bge-small-en-v1.5 --revision refs/pr/5
    ports:
      - "8081:80"
    volumes:
      - ./data:/data
